sudo: required

services: docker

before_install:
  - docker-compose up --build -d
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com

script:
  - docker-compose exec --env 'RAILS_ENV=test' web bash rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web bash rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web bash rails test

deploy:
  provider: script
  script:
    docker build -t registory.heroku.com/$$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push egistory.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app $HEROKU_APP_NAME rails db:migrate
  on:
    branch: master
