sudo: required

services: docker

before_install:
  - docker-compose up --build -d


script:
  - docker-compose exexc --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exexc --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exexc --env 'RAILS_ENV=test' web rails test
